on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
    - name: get code
      uses: actions/checkout@v3
    - name: compiling
      run: |
        sh build.sh
    - uses: actions/upload-artifact@v3
      name: save build
      with:
        name: curl-static
        path: /tmp/release


